export const PROJECT_MANAGEMENT_CACHE_VERSION = 1;
export const PROJECT_MANAGEMENT_CACHE_TTL_MS = 60 * 60 * 1000;
export const PROJECT_MANAGEMENT_REFRESH_INTERVAL_MS = PROJECT_MANAGEMENT_CACHE_TTL_MS;
export const PROJECT_MANAGEMENT_CACHE_KEY = `project-management-dashboard:v${PROJECT_MANAGEMENT_CACHE_VERSION}`;
